export const MOCK_LISTA_ASEGURADOS_ACTIVO = [
    {
        "cod_asegurado": 52959,
        "apellido": "Vceradu Predolts S.U",
        "nombre": ".",
        "desc_asegurado": "Aceradu Predolts S.U.",
        "calle": "ED. YI MENA",
        "nro_puerta": 666,
        "piso": "7",
        "depto": null,
        "domicilio": "D. YI MENA 666 7 ",
        "cod_provincia": 1,
        "desc_provincia": "C.A.B.A.",
        "desc_localidad": "CAPITAL FEDERAL",
        "cod_postal": "1084",
        "nacionalidad": null,
        "telefono": "4866-1877",
        "celular": null,
        "fax": null,
        "email": null,
        "cod_documento": null,
        "desc_tipo_documento": null,
        "nro_documento": null,
        "nro_cuit": 20715856523,
        "digito_cuit": "20-71585652-3",
        "cod_condicion_fiscal": "S",
        "desc_condicion_fiscal": "RESP.  INSCRIPTO",
        "conv_iib": "M",
        "desc_iibb": "Convenio Multilateral",
        "sexo": null,
        "desc_sexo": null,
        "personeria": "J",
        "desc_personeria": "Persona Juridica",
        "estado_civil": null,
        "desc_estado_civil": null,
        "fec_nacim": null,
        "edad": null,
        "desc_causa_bloqueo": "MOROSIDAD proc 284",
        "cod_categoria_bloqueo": "N",
        "desc_categoria_bloqueo": "Normal",
        "fecha_bloqueo": "07/05/2019",
        "cod_situacion_bloqueo": "B",
        "desc_situacion_bloqueo": "Bloqueado",
        "es_pep": null,
        "es_sujeto_obligado": "S",
        "tipo_cliente": "O",
        "es_cliente_inusual": "S",
        "nivel_riesgo": 1,
        "cantidad_polizas": 3,
        "importe_prima_emitida": 161769.77,
        "importe_suma_asegurada": 65150000,
        "cantidad_siniestros": 3,
        "indemnizacion_siniestros": 17196892.68
    },
    {
        "cod_asegurado": 52959,
        "apellido": "Eceradu Predolts S.U",
        "nombre": ".",
        "desc_asegurado": "Vceradu Predolts S.U.",
        "calle": "ED. YI MENA",
        "nro_puerta": 666,
        "piso": "7",
        "depto": null,
        "domicilio": "WD. YI MENA 666 7 ",
        "cod_provincia": 1,
        "desc_provincia": "C.A.B.A.",
        "desc_localidad": "CAPITAL FEDERAL",
        "cod_postal": "1084",
        "nacionalidad": null,
        "telefono": "4866-1877",
        "celular": null,
        "fax": null,
        "email": null,
        "cod_documento": null,
        "desc_tipo_documento": null,
        "nro_documento": null,
        "nro_cuit": 20715856523,
        "digito_cuit": "20-71585652-3",
        "cod_condicion_fiscal": "S",
        "desc_condicion_fiscal": "RESP.  INSCRIPTO",
        "conv_iib": "M",
        "desc_iibb": "Convenio Multilateral",
        "sexo": null,
        "desc_sexo": null,
        "personeria": "J",
        "desc_personeria": "Persona Juridica",
        "estado_civil": null,
        "desc_estado_civil": null,
        "fec_nacim": null,
        "edad": null,
        "desc_causa_bloqueo": "MOROSIDAD proc 284",
        "cod_categoria_bloqueo": "N",
        "desc_categoria_bloqueo": "Normal",
        "fecha_bloqueo": "07/05/2019",
        "cod_situacion_bloqueo": "B",
        "desc_situacion_bloqueo": "Bloqueado",
        "es_pep": null,
        "es_sujeto_obligado": "S",
        "tipo_cliente": "O",
        "es_cliente_inusual": "S",
        "nivel_riesgo": 1,
        "cantidad_polizas": 3,
        "importe_prima_emitida": 161769.77,
        "importe_suma_asegurada": 65150000,
        "cantidad_siniestros": 3,
        "indemnizacion_siniestros": 17196892.68
    },
    {
        "cod_asegurado": 52959,
        "apellido": "Vceradu Predolts S.U",
        "nombre": ".",
        "desc_asegurado": "Vceradu Predolts S.U.",
        "calle": "ED. YI MENA",
        "nro_puerta": 666,
        "piso": "7",
        "depto": null,
        "domicilio": "ED. YI MENA 666 7 ",
        "cod_provincia": 1,
        "desc_provincia": "C.A.B.A.",
        "desc_localidad": "CAPITAL FEDERAL",
        "cod_postal": "1084",
        "nacionalidad": null,
        "telefono": "4866-1877",
        "celular": null,
        "fax": null,
        "email": null,
        "cod_documento": null,
        "desc_tipo_documento": null,
        "nro_documento": null,
        "nro_cuit": 20715856523,
        "digito_cuit": "20-71585652-3",
        "cod_condicion_fiscal": "S",
        "desc_condicion_fiscal": "RESP.  INSCRIPTO",
        "conv_iib": "M",
        "desc_iibb": "Convenio Multilateral",
        "sexo": null,
        "desc_sexo": null,
        "personeria": "J",
        "desc_personeria": "Persona Juridica",
        "estado_civil": null,
        "desc_estado_civil": null,
        "fec_nacim": null,
        "edad": null,
        "desc_causa_bloqueo": "MOROSIDAD proc 284",
        "cod_categoria_bloqueo": "N",
        "desc_categoria_bloqueo": "Normal",
        "fecha_bloqueo": "07/05/2019",
        "cod_situacion_bloqueo": "B",
        "desc_situacion_bloqueo": "Bloqueado",
        "es_pep": null,
        "es_sujeto_obligado": "S",
        "tipo_cliente": "O",
        "es_cliente_inusual": "S",
        "nivel_riesgo": 1,
        "cantidad_polizas": 3,
        "importe_prima_emitida": 161769.77,
        "importe_suma_asegurada": 65150000,
        "cantidad_siniestros": 3,
        "indemnizacion_siniestros": 17196892.68
    }
];